### ISSUE TITLE
Block syntax highlighting of config and wxs is not support at all

### ISSUE THREAD

**Issue by ZhongyiChen** [hom/vscode-wepy-extension#3]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win10
- Vetur version: 0.24.0
- VS Code version: 1.45.1

## Problem

The blocks of "config" and "wxs" were rendered with no colors. But the other blocks could be rendered as normal, namely with a lot of colors.

**Comment by ZhongyiChen** [comment]
Reload the Extension "Vetur" and then the problem would be solved.

**Comment by hom** [comment]
Because of this extension use Vetur to highlight, so it maybe have some bugs, you can disable Vetur when use Wepy to fix it now, I will fix it soon
